export const NAVIGATION = {
  auth: {
    login: '/auth/login',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  admin: {
    dashboard: '/admin/dashboard',
    branches: '/admin/branches',
    users: '/admin/users',
    inventory: '/admin/inventory',
    purchase: '/admin/purchase',
    request: '/admin/request',
    reports: '/admin/reports',
    purchaseTrend: '/admin/purchase-trend',
    analytics: '/admin/analytics',
    chat: '/admin/chat',
  },
  branch: {
    dashboard: '/branch/dashboard',
    inventory: '/branch/inventory',
    purchase: '/branch/purchase',
    requestedpurchase: '/branch/requestedpurchase',
    sales: '/branch/sales',
    purchaseTrend: '/branch/purchase-trend',
    analytics: '/branch/analytics',
    alerts: '/branch/alerts',
    chat: '/branch/chat',
  },
};
